export const FETCH_MOVIE_FULFILLED = 'FETCH_MOVIE_FULFILLED';
export const FETCH_MOVIE_REJECTED = 'FETCH_MOVIE_REJECTED';
export const FETCH_MOVIE_DEETS_FULFILLED = 'FETCH_MOVIE_DEETS_FULFILLED';
export const FETCH_MOVIE_DEETS_REJECTED = 'FETCH_MOVIE_DEETS_REJECTED';
